### ISSUE TITLE
Unauthorized Error During Streamable Export

### ISSUE THREAD

**Issue by dcalhoun** [kevva/kap-streamable#1]
Attempting to export a Kap throws a 401 unauthorized error.

```
Error: Response code 401 (UNAUTHORIZED)
    at stream.catch.then.data (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/got/index.js:341:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

## Steps to Reproduce

1. Install `kap-streamable` following the README guides.
1. Capture screen using Kap.
1. Click "MP4" and then "Share on Streamable".

## Expected Result

The capture is exported and uploaded to Streamable.

## Actual Result

The capture export fails with the aforementioned error.

## Notes

- Kap 2.1.2 (2.1.2.777)
- kap-streamable 0.1.0
- macOS 10.13.6 (17G65)
- Uninstalling and re-installing the plugin does not seem to resolve the issue.
- Logging into my Streamable account in Safari works fine, I am able to upload and share videos.

<img width="532" alt="kap-streamable-error" src="https://user-images.githubusercontent.com/438664/42693130-b5a81dc8-8673-11e8-9bda-7075fe3d0dd0.png">

**Comment by cenourinha** [comment]
I'm having this problem too.

**Comment by livejamie** [comment]
Still occuring
